import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import FirebaseWrapper from "./components/context/app_wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <FirebaseWrapper>
      <html lang="en">
        <head>
          <script src="https://unpkg.com/phosphor-icons"></script>
        </head>
        <body className={`w-[100vw] h-[100vh] overflow-hidden ${inter.className}`}>
          {children}
        </body>
      </html>
    </FirebaseWrapper>
  );
}
